### ISSUE TITLE
Few problems

### ISSUE THREAD

**Issue by Bono2007** [vad-ii-k/Digital-Planner#1]
Error "... await generate_html(planner, './dest/index.html')", i had to mkdir ./dest 
Then playwright install
Then install node.js
Python 3.11
Node v18.16.0
npm 9.5.1

Only index.html, no main.css

Then : 
------------------------------------------------------------------------------------------------
### _Traceback (most recent call last):
  File "C:\Users\llc\Digital-Planner\planner_generator.py", line 59, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\llc\Digital-Planner\planner_generator.py", line 55, in main
    await generate_pdf('./dest/index.html', './dest/main.css', './dest/planner.pdf')
  File "C:\Users\llc\Digital-Planner\planner_generator.py", line 42, in generate_pdf
    await page.add_style_tag(path=abspath(css_file_path))
  File "C:\Users\llc\AppData\Roaming\Python\Python311\site-packages\playwright\async_api\_generated.py", line 8829, in add_style_tag
    await self._impl_obj.add_style_tag(url=url, path=path, content=content)
  File "C:\Users\llc\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_page.py", line 449, in add_style_tag
    return await self._main_frame.add_style_tag(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\llc\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_frame.py", line 467, in add_style_tag
    (await async_readfile(path)).decode()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\llc\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_helper.py", line 352, in async_readfile
    return await loop.run_in_executor(None, inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\llc\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_helper.py", line 348, in inner
    with open(file, "rb") as fh:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\llc\\Digital-Planner\\dest\\main.css'_

What i did : 
`npm init -y`
`npm install tailwindcss postcss postcss-cli autoprefixer --save-dev`
create a file package.json :
`{
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build-css": "postcss src/input.css -o dest/main.css"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "postcss": "^8.4.21",
    "postcss-cli": "^10.1.0",
    "tailwindcss": "^3.3.1"
  },
  "name": "digital-planner",
  "version": "1.0.0",
  "main": "tailwind.config.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}`
`npm run build-css`

And it works

**Comment by vad-ii-k** [comment]
Hi!

Here is a quick **installation** instruction (you must have python3, npm and playwright installed):
```powershell
npm i
pip install jinja2 playwright
``` 

To **generate** a planner, run the command:
```powershell
npm run build
```
